In [1]:
import pandas as pd

In [4]:
df = pd.read_csv('../data/brca_tcga_gdc_clinical_data.tsv', sep='\t')
df.head()

,Study ID,Patient ID,Sample ID,Diagnosis Age,American Joint Committee on Cancer Publication Version Type,Biopsy Site,Cancer Type,Cancer Type Detailed,Last Communication Contact from Initial Pathologic Diagnosis Date,Birth from Initial Pathologic Diagnosis Date,...,Project Identifier,Project Name,Project State,Race Category,Number of Samples Per Patient,Sample Type,Sample type id,Sex,Patient's Vital Status,Year of Diagnosis
0,brca_tcga_gdc,TCGA-3C-AAAU,TCGA-3C-AAAU-01,55.0,6th,Breast,Invasive Breast Carcinoma,Invasive Breast Carcinoma,3767.0,-20211.0,...,TCGA-BRCA,Invasive Breast Carcinoma,released,WHITE,1,Primary Tumor,1,Female,Alive,2004.0
1,brca_tcga_gdc,TCGA-3C-AALI,TCGA-3C-AALI-01,50.0,6th,Breast,Invasive Breast Carcinoma,Invasive Breast Carcinoma,3801.0,-18538.0,...,TCGA-BRCA,Invasive Breast Carcinoma,released,BLACK OR AFRICAN AMERICAN,1,Primary Tumor,1,Female,Alive,2003.0
2,brca_tcga_gdc,TCGA-3C-AALJ,TCGA-3C-AALJ-01,62.0,7th,Breast,Invasive Breast Carcinoma,Invasive Breast Carcinoma,1228.0,-22848.0,...,TCGA-BRCA,Invasive Breast Carcinoma,released,BLACK OR AFRICAN AMERICAN,1,Primary Tumor,1,Female,Alive,2011.0
3,brca_tcga_gdc,TCGA-3C-AALK,TCGA-3C-AALK-01,52.0,7th,Breast,Invasive Breast Carcinoma,Invasive Breast Carcinoma,1217.0,-19074.0,...,TCGA-BRCA,Invasive Breast Carcinoma,released,BLACK OR AFRICAN AMERICAN,1,Primary Tumor,1,Female,Alive,2011.0
4,brca_tcga_gdc,TCGA-4H-AAAK,TCGA-4H-AAAK-01,50.0,7th,Breast,Invasive Breast Carcinoma,Invasive Breast Carcinoma,158.0,-18371.0,...,TCGA-BRCA,Invasive Breast Carcinoma,released,WHITE,1,Primary Tumor,1,Female,Alive,2013.0

In [5]:
df.columns

Index(['Study ID', 'Patient ID', 'Sample ID', 'Diagnosis Age',
       'American Joint Committee on Cancer Publication Version Type',
       'Biopsy Site', 'Cancer Type', 'Cancer Type Detailed',
       'Last Communication Contact from Initial Pathologic Diagnosis Date',
       'Birth from Initial Pathologic Diagnosis Date',
       'Death from Initial Pathologic Diagnosis Date', 'Disease Free (Months)',
       'Disease Free Status', 'Disease Type', 'Ethnicity Category',
       'Fraction Genome Altered', 'ICD-10 Classification', 'Is FFPE',
       'Morphology', 'Mutation Count', 'Oncotree Code',
       'Overall Survival (Months)', 'Overall Survival Status',
       'Other Patient ID', 'Other Sample ID', 'AJCC Pathologic M-Stage',
       'AJCC Pathologic N-Stage', 'AJCC Pathologic Stage',
       'AJCC Pathologic T-Stage', 'Primary Diagnosis',
       'Patient Primary Tumor Site', 'Prior Malignancy', 'Prior Treatment',
       'Project Identifier', 'Project Name', 'Project State', 'Race Category',
       'Number of Samples Per Patient', 'Sample Type', 'Sample type id', 'Sex',
       'Patient's Vital Status', 'Year of Diagnosis'],
      dtype='object')

In [9]:
df['Overall Survival (Months)'].value_counts(dropna=False)

Overall Survival (Months)
0.000000      20
0.328515      15
12.647832      7
11.990802      6
12.319317      5
              ..
18.002628      1
78.350854      1
121.846255     1
73.784494      1
87.187911      1
Name: count, Length: 829, dtype: int64

In [13]:
df["Patient's Vital Status"].value_counts(dropna=False)

Patient's Vital Status
Alive    949
Dead     155
NaN        1
Name: count, dtype: int64

In [7]:
df_filtered = pd.read_csv('/scratch/2370352/my-research/repo/src/data/files/tcga_brca/clinical_data_all_filtered.csv')
df_filtered.head()

,case_id,slide_id,submitter_id,tumor_type,project_id,site_of_resection_or_biopsy,sex,OncotreeCode,cancer_type_detailed,tissue_source_site,...,dss_cr_censorship,dss_cr_survival_days,dfi_cr_censorship,dfi_cr_survival_days,pfi_cr_censorship,pfi_cr_survival_days,pfi_v1_cr_censorship,pfi_v1_cr_survival_days,pfi_v2_cr_censorship,pfi_v2_cr_survival_days
0,TCGA-3C-AALI,TCGA-3C-AALI-01Z-00-DX2.CF4496E0-AB52-4F3E-BDF...,TCGA-3C-AALI,Primary,TCGA-BRCA,"Breast, NOS",F,IDC,Breast Invasive Ductal Carcinoma,3C,...,1.0,4005.0,1.0,4005.0,1.0,4005.0,1.0,4005.0,1.0,4005.0
1,TCGA-3C-AALI,TCGA-3C-AALI-01Z-00-DX1.F6E9A5DF-D8FB-45CF-B4B...,TCGA-3C-AALI,Primary,TCGA-BRCA,"Breast, NOS",F,IDC,Breast Invasive Ductal Carcinoma,3C,...,1.0,4005.0,1.0,4005.0,1.0,4005.0,1.0,4005.0,1.0,4005.0
2,TCGA-3C-AALJ,TCGA-3C-AALJ-01Z-00-DX2.62DFE56B-B84C-40F9-962...,TCGA-3C-AALJ,Primary,TCGA-BRCA,"Breast, NOS",F,IDC,Breast Invasive Ductal Carcinoma,3C,...,1.0,1474.0,1.0,1474.0,1.0,1474.0,1.0,1474.0,1.0,1474.0
3,TCGA-3C-AALJ,TCGA-3C-AALJ-01Z-00-DX1.777C0957-255A-42F0-9EE...,TCGA-3C-AALJ,Primary,TCGA-BRCA,"Breast, NOS",F,IDC,Breast Invasive Ductal Carcinoma,3C,...,1.0,1474.0,1.0,1474.0,1.0,1474.0,1.0,1474.0,1.0,1474.0
4,TCGA-3C-AALK,TCGA-3C-AALK-01Z-00-DX1.4E6EB156-BB19-410F-878...,TCGA-3C-AALK,Primary,TCGA-BRCA,"Breast, NOS",F,IDC,Breast Invasive Ductal Carcinoma,3C,...,1.0,1448.0,NaN,NaN,1.0,1448.0,1.0,1448.0,1.0,1448.0

In [14]:
df_filtered.columns

Index(['case_id', 'slide_id', 'submitter_id', 'tumor_type', 'project_id',
       'site_of_resection_or_biopsy', 'sex', 'OncotreeCode',
       'cancer_type_detailed', 'tissue_source_site', 'is_code_valid', 'mpp',
       'op', 'level0_mag', 'OncoTreeSiteCode',
       'age_at_initial_pathologic_diagnosis', 'race',
       'ajcc_pathologic_tumor_stage', 'clinical_stage', 'histological_type',
       'histological_grade', 'initial_pathologic_dx_year', 'menopause_status',
       'birth_days_to', 'vital_status', 'tumor_status', 'last_contact_days_to',
       'death_days_to', 'cause_of_death', 'new_tumor_event_type',
       'new_tumor_event_site', 'new_tumor_event_site_other',
       'new_tumor_event_dx_days_to', 'treatment_outcome_first_course',
       'margin_status', 'residual_tumor', 'os_censorship', 'os_survival_days',
       'dss_censorship', 'dss_survival_days', 'dfi_censorship',
       'dfi_survival_days', 'pfi_censorship', 'pfi_survival_days', 'redaction',
       'pfi_v1_censorship', 'pfi_v1_survival_days', 'pfi_v2_censorship',
       'pfi_v2_survival_days', 'pfs_censorship', 'pfs_survival_days',
       'dss_cr_censorship', 'dss_cr_survival_days', 'dfi_cr_censorship',
       'dfi_cr_survival_days', 'pfi_cr_censorship', 'pfi_cr_survival_days',
       'pfi_v1_cr_censorship', 'pfi_v1_cr_survival_days',
       'pfi_v2_cr_censorship', 'pfi_v2_cr_survival_days'],
      dtype='object')

In [10]:
df_filtered['dss_survival_days'].value_counts(dropna=False)

dss_survival_days
3650.0    35
10.0      13
365.0      6
304.0      5
302.0      5
          ..
2222.0     1
3022.0     1
343.0      1
345.0      1
457.0      1
Name: count, Length: 650, dtype: int64

In [11]:
n_missing = df_filtered["dss_survival_days"].isna().sum()
n_missing

0

In [12]:
df_filtered['dss_censorship'].value_counts(dropna=False)

dss_censorship
1.0    869
0.0     59
Name: count, dtype: int64

In [15]:
df_filtered['vital_status'].value_counts(dropna=False)

vital_status
Alive    824
Dead     104
Name: count, dtype: int64

In [16]:
df_filtered_censored = df_filtered[df_filtered['dss_censorship'] == 1]

In [17]:
df_filtered_censored['vital_status'].value_counts(dropna=False)

vital_status
Alive    824
Dead      45
Name: count, dtype: int64

In [18]:
df_filtered_censored_dead = df_filtered_censored[df_filtered_censored['vital_status'] == 'Dead']

In [20]:
df_filtered_censored_dead['cause_of_death'].value_counts()

cause_of_death
[Not Available]    45
Name: count, dtype: int64

In [21]:
df_filtered['cause_of_death'].value_counts()

cause_of_death
[Not Available]    928
Name: count, dtype: int64

In [3]:
df_scgpt = pd.read_csv('../data/scgpt_embeddings/scgpt_adata_TCGA-BRCA.star_counts_pancancer_hvg_0.csv')

In [4]:
df_scgpt.head()

,Unnamed: 0,emb1,emb2,emb3,emb4,emb5,emb6,emb7,emb8,emb9,...,emb503,emb504,emb505,emb506,emb507,emb508,emb509,emb510,emb511,emb512
0,TCGA-D8-A146,0.043294,0.013521,-0.006708,0.028044,-0.007037,-0.018619,0.008401,0.013831,0.040137,...,-0.020429,0.006554,0.000725,-0.013950,-0.021471,-0.039761,-0.012966,-0.019790,-0.011310,-0.025579
1,TCGA-AQ-A0Y5,0.043838,0.013272,-0.010138,0.021309,-0.007207,-0.023075,0.006517,0.018669,0.035314,...,-0.016860,0.006143,0.005009,-0.020482,-0.023950,-0.029406,-0.007827,-0.014673,-0.011220,-0.024791
2,TCGA-C8-A274,0.046057,0.015006,0.001564,0.016241,-0.015095,-0.021837,0.008514,0.010656,0.035728,...,-0.024120,0.008117,0.005158,-0.021526,-0.010408,-0.023719,-0.012975,-0.014249,-0.004355,-0.022878
3,TCGA-BH-A0BD,0.032711,0.007662,-0.004046,0.028065,-0.010397,-0.022572,0.000236,0.012181,0.027818,...,-0.020089,0.004229,0.007407,-0.019250,-0.018030,-0.033586,-0.016679,-0.015470,-0.013320,-0.021056
4,TCGA-B6-A1KC,0.051560,0.029326,-0.014469,0.018090,0.005523,-0.028185,0.014616,0.021186,0.004908,...,-0.020021,0.013135,0.001996,-0.018905,-0.009419,-0.019154,-0.019629,0.009692,0.001613,-0.031149

Unnamed: 0
TCGA-A1-A0SN    1
TCGA-D8-A146    1
TCGA-AQ-A0Y5    1
TCGA-C8-A274    1
TCGA-BH-A0BD    1
               ..
TCGA-AO-A1KQ    1
TCGA-E2-A1LI    1
TCGA-BH-A18L    1
TCGA-B6-A0WV    1
TCGA-E2-A1LE    1
Name: count, Length: 1095, dtype: int64

In [4]:
df = pd.read_csv("/scratch/2370352/my-research/repo/src/data/files/tcga_brca/splits/0/train_filtered.csv")

In [5]:
import numpy as np
import pandas as pd

times = df['dss_survival_days'].values
cens = df['dss_censorship'].values  # 0=event, 1=censored

# Funkcja censoringu w surowym ujęciu
df = pd.DataFrame({'dss_survival_days': times, 'dss_censorship': cens})
df = df.sort_values('dss_survival_days')

# Sprawdzenie, czy w którymś czasie wszyscy są ocenzurowani
for t in np.unique(times):
    subset = df[df['dss_survival_days'] == t]
    if subset['dss_censorship'].sum() == len(subset):
        print(f"Problem: wszystkie obserwacje w czasie {t} są ocenzurowane")

Problem: wszystkie obserwacje w czasie 1.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 5.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 7.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 8.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 9.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 10.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 11.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 30.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 31.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 34.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 51.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 70.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 76.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 78.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 80.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 98.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 118.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 134.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 149.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 158.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 163.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 170.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 172.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 178.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 196.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 210.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 213.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 214.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 216.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 218.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 231.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 242.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 250.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 252.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 258.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 273.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 274.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 275.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 285.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 293.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 297.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 302.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 303.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 304.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 313.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 317.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 322.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 323.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 326.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 328.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 334.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 336.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 337.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 343.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 345.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 350.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 352.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 358.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 363.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 366.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 370.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 371.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 373.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 375.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 376.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 379.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 380.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 381.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 382.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 383.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 392.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 393.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 394.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 396.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 402.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 403.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 404.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 408.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 411.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 413.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 414.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 416.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 417.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 421.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 423.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 424.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 426.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 428.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 435.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 437.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 439.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 440.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 441.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 447.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 448.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 450.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 451.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 455.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 457.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 458.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 461.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 463.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 467.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 470.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 476.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 477.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 488.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 489.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 495.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 496.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 501.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 504.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 508.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 510.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 511.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 513.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 518.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 519.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 521.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 523.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 525.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 526.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 528.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 529.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 530.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 531.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 532.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 533.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 541.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 546.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 547.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 549.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 552.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 554.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 562.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 566.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 567.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 568.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 572.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 574.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 575.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 577.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 579.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 584.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 585.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 586.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 588.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 591.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 594.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 595.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 596.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 598.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 600.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 607.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 608.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 616.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 618.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 620.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 622.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 624.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 626.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 627.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 629.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 631.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 635.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 640.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 641.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 643.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 644.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 646.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 651.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 652.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 655.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 658.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 659.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 660.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 661.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 666.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 672.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 675.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 677.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 679.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 680.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 683.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 694.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 698.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 702.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 703.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 707.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 710.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 714.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 715.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 718.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 723.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 724.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 726.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 728.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 734.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 745.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 747.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 748.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 752.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 759.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 760.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 761.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 762.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 765.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 767.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 769.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 789.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 791.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 795.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 798.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 806.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 819.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 822.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 829.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 856.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 858.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 865.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 867.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 875.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 878.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 883.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 890.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 907.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 908.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 911.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 915.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 923.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 931.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 942.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 943.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 952.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 954.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 965.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 968.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 972.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 973.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 974.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 975.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 984.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 990.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 991.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 996.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 997.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 1001.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 1004.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 1006.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 1007.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 1010.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 1025.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 1026.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 1042.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 1043.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 1047.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 1051.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 1062.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 1066.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 1074.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 1079.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 1085.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 1093.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 1099.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 1104.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 1119.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 1121.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 1124.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 1133.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 1138.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 1139.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 1140.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 1141.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 1142.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 1156.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 1163.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 1165.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 1179.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 1191.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 1196.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 1203.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 1208.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 1210.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 1217.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 1220.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 1229.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 1234.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 1246.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 1247.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 1251.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 1270.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 1275.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 1277.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 1286.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 1288.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 1291.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 1301.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 1308.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 1309.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 1324.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 1326.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 1347.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 1351.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 1359.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 1363.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 1371.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 1417.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 1430.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 1434.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 1437.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 1439.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 1448.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 1463.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 1471.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 1474.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 1476.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 1477.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 1492.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 1516.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 1519.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 1522.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 1523.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 1528.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 1532.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 1534.0 są ocenzurowane
Problem: wszystkie obserwacje w czasie 1535.0 są ocenzurowane