In [1]:
import cellxgene_census
import pandas as pd
import scanpy as sc

In [2]:
cell_gene_dir = "../../data/censusxgene"

In [14]:
with cellxgene_census.open_soma(census_version="2025-11-08") as census:

    cell_metadata = cellxgene_census.get_obs(
        census,
        "homo_sapiens",
        value_filter = "sex == 'female'  and tissue == 'lung'", #and cell_type == 'neuron'
        # column_names = ["assay", "cell_type", "tissue", "tissue_general", "suspension_type", "disease"]
    )

In [15]:
cell_metadata

,soma_joinid,dataset_id,assay,assay_ontology_term_id,cell_type,cell_type_ontology_term_id,development_stage,development_stage_ontology_term_id,disease,disease_ontology_term_id,...,tissue,tissue_ontology_term_id,tissue_type,tissue_general,tissue_general_ontology_term_id,raw_sum,nnz,raw_mean_nnz,raw_variance_nnz,n_measured_vars
0,31189,703f00e6-b996-48e5-bc34-00c41b9876f4,10x 5' v1,EFO:0011025,Schwann cell,CL:0002573,15th week post-fertilization stage,HsapDv:0000052,normal,PATO:0000461,...,lung,UBERON:0002048,tissue,lung,UBERON:0002048,2087.0,1357,1.537951,5.754643,16035
1,31190,703f00e6-b996-48e5-bc34-00c41b9876f4,10x 5' v1,EFO:0011025,Schwann cell,CL:0002573,15th week post-fertilization stage,HsapDv:0000052,normal,PATO:0000461,...,lung,UBERON:0002048,tissue,lung,UBERON:0002048,14733.0,4268,3.451968,107.457969,16035
2,31191,703f00e6-b996-48e5-bc34-00c41b9876f4,10x 5' v1,EFO:0011025,immature Schwann cell,CL:0002377,Carnegie stage 19,HsapDv:0000026,normal,PATO:0000461,...,lung,UBERON:0002048,tissue,lung,UBERON:0002048,5174.0,1797,2.879243,53.412470,16035
3,31192,703f00e6-b996-48e5-bc34-00c41b9876f4,10x 5' v1,EFO:0011025,neuron,CL:0000540,Carnegie stage 19,HsapDv:0000026,normal,PATO:0000461,...,lung,UBERON:0002048,tissue,lung,UBERON:0002048,8107.0,3033,2.672931,31.431249,16035
4,31193,703f00e6-b996-48e5-bc34-00c41b9876f4,10x 5' v1,EFO:0011025,neuron,CL:0000540,Carnegie stage 19,HsapDv:0000026,normal,PATO:0000461,...,lung,UBERON:0002048,tissue,lung,UBERON:0002048,4760.0,2052,2.319688,21.998188,16035
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2796558,156004908,53d208b0-2cfd-4366-9866-c3c6114081bc,10x 3' v3,EFO:0009922,macrophage,CL:0000235,59-year-old stage,HsapDv:0000153,normal,PATO:0000461,...,lung,UBERON:0002048,tissue,lung,UBERON:0002048,17839.0,4058,4.396008,521.971066,60606
2796559,156004909,53d208b0-2cfd-4366-9866-c3c6114081bc,10x 3' v3,EFO:0009922,pulmonary alveolar type 2 cell,CL:0002063,59-year-old stage,HsapDv:0000153,normal,PATO:0000461,...,lung,UBERON:0002048,tissue,lung,UBERON:0002048,12325.0,3396,3.629270,1034.633358,60606
2796560,156004910,53d208b0-2cfd-4366-9866-c3c6114081bc,10x 3' v3,EFO:0009922,macrophage,CL:0000235,59-year-old stage,HsapDv:0000153,normal,PATO:0000461,...,lung,UBERON:0002048,tissue,lung,UBERON:0002048,14947.0,3758,3.977382,567.460494,60606
2796561,156004911,53d208b0-2cfd-4366-9866-c3c6114081bc,10x 3' v3,EFO:0009922,pulmonary alveolar type 2 cell,CL:0002063,59-year-old stage,HsapDv:0000153,normal,PATO:0000461,...,lung,UBERON:0002048,tissue,lung,UBERON:0002048,14817.0,3615,4.098755,1885.680062,60606
2796562,156004912,53d208b0-2cfd-4366-9866-c3c6114081bc,10x 3' v3,EFO:0009922,capillary endothelial cell,CL:0002144,59-year-old stage,HsapDv:0000153,normal,PATO:0000461,...,lung,UBERON:0002048,tissue,lung,UBERON:0002048,4982.0,2241,2.223115,32.871626,60606

In [4]:
with cellxgene_census.open_soma(census_version="2025-11-08") as census:

    cell_adata = cellxgene_census.get_anndata(
        census,
        "homo_sapiens",
        obs_value_filter = "sex == 'female' and tissue == 'lung' and cell_type in ['neuron', 'macrophage']",
        column_names = ["assay", "cell_type", "tissue", "tissue_general", "suspension_type", "disease"]
    )
    cell_adata

/tmp/ipykernel_571030/17705031.py:3: FutureWarning: The argument `column_names` is deprecated and will be removed in a future release. Please use `obs_column_names` and `var_column_names` instead.
  cell_adata = cellxgene_census.get_anndata(
/scratch/2370352/conda/envs/myenv/lib/python3.9/site-packages/anndata/_core/aligned_df.py:68: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)
/scratch/2370352/conda/envs/myenv/lib/python3.9/site-packages/anndata/_core/aligned_df.py:68: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)

In [8]:
sc.pp.normalize_total(cell_adata, target_sum=1e4, inplace=False)
sc.pp.log1p(cell_adata)

In [9]:
cell_adata

AnnData object with n_obs × n_vars = 1176 × 61497
    obs: 'soma_joinid', 'dataset_id', 'assay', 'assay_ontology_term_id', 'cell_type', 'cell_type_ontology_term_id', 'development_stage', 'development_stage_ontology_term_id', 'disease', 'disease_ontology_term_id', 'donor_id', 'is_primary_data', 'observation_joinid', 'self_reported_ethnicity', 'self_reported_ethnicity_ontology_term_id', 'sex', 'sex_ontology_term_id', 'suspension_type', 'tissue', 'tissue_ontology_term_id', 'tissue_type', 'tissue_general', 'tissue_general_ontology_term_id', 'raw_sum', 'nnz', 'raw_mean_nnz', 'raw_variance_nnz', 'n_measured_vars'
    var: 'soma_joinid', 'feature_id', 'feature_name', 'feature_type', 'feature_length', 'nnz', 'n_measured_obs'

In [9]:
cell_adata.write("../../data/censusxgene/female_lung_neuron_vs_macrophage_norm.h5ad")

In [10]:
cell_adata.X

<1176x61497 sparse matrix of type '<class 'numpy.float32'>'
	with 2282559 stored elements in Compressed Sparse Row format>

In [19]:
type(cell_adata.X)

scipy.sparse._csr.csr_matrix

In [20]:
cell_adata.X[:5, :5]

<5x5 sparse matrix of type '<class 'numpy.float32'>'
	with 4 stored elements in Compressed Sparse Row format>

In [21]:
cell_adata.X[:5, :5].toarray()

array([[0., 2., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)

In [22]:
1176 * 61497

72320472

In [ ]:
72320472 - 2282559

70037913

In [25]:
adata_pd = pd.DataFrame(
    cell_adata.X[:5, :5].toarray() if hasattr(cell_adata.X, "toarray") else cell_adata.X[:5, :5],
    index=cell_adata.obs_names[:5],
    columns=cell_adata.var_names[:5]
)

In [26]:
adata_pd

     0    1    2    3    4
0  0.0  2.0  0.0  0.0  0.0
1  0.0  0.0  0.0  0.0  0.0
2  0.0  2.0  0.0  0.0  0.0
3  1.0  1.0  0.0  0.0  0.0
4  0.0  0.0  0.0  0.0  0.0

In [27]:
cell_adata.var_names[:5]

Index(['0', '1', '2', '3', '4'], dtype='object')

In [28]:
cell_adata.var.head()

,soma_joinid,feature_id,feature_name,feature_type,feature_length,nnz,n_measured_obs
0,0,ENSG00000237491,LINC01409,lncRNA,1089,12566788,142365045
1,1,ENSG00000188976,NOC2L,protein_coding,1244,26123981,158649077
2,2,ENSG00000187642,PERM1,protein_coding,2765,824852,146911882
3,3,ENSG00000272512,ENSG00000272512,lncRNA,2086,1190083,141564179
4,4,ENSG00000188290,HES4,protein_coding,961,24610287,158630852

In [29]:
cell_adata.var.columns

Index(['soma_joinid', 'feature_id', 'feature_name', 'feature_type',
       'feature_length', 'nnz', 'n_measured_obs'],
      dtype='object')

In [3]:
with cellxgene_census.open_soma(census_version="2025-11-08") as census:

    cell_metadata_all = cellxgene_census.get_obs(
        census,
        "homo_sapiens",
        # value_filter = "tissue == 'breast'",
        # value_filter = "sex == 'female' and cell_type == 'neuron' and tissue == 'lung'",
        # column_names = ["assay", "cell_type", "tissue", "tissue_general", "suspension_type", "disease"]
    )
    cell_metadata_all

In [4]:
cell_metadata_all

,soma_joinid,dataset_id,assay,assay_ontology_term_id,cell_type,cell_type_ontology_term_id,development_stage,development_stage_ontology_term_id,disease,disease_ontology_term_id,...,tissue,tissue_ontology_term_id,tissue_type,tissue_general,tissue_general_ontology_term_id,raw_sum,nnz,raw_mean_nnz,raw_variance_nnz,n_measured_vars
0,0,d7476ae2-e320-4703-8304-da5c42627e71,10x 3' v3,EFO:0009922,endothelial cell,CL:0000115,29-year-old stage,HsapDv:0000123,breast cancer,MONDO:0007254,...,liver,UBERON:0002107,tissue,liver,UBERON:0002107,19636.0,7152,2.745526,696.616257,12621
1,1,d7476ae2-e320-4703-8304-da5c42627e71,10x 3' v3,EFO:0009922,malignant cell,CL:0001064,29-year-old stage,HsapDv:0000123,breast cancer,MONDO:0007254,...,liver,UBERON:0002107,tissue,liver,UBERON:0002107,17245.0,5382,3.204199,394.569148,12621
2,2,d7476ae2-e320-4703-8304-da5c42627e71,10x 3' v3,EFO:0009922,fibroblast,CL:0000057,29-year-old stage,HsapDv:0000123,breast cancer,MONDO:0007254,...,liver,UBERON:0002107,tissue,liver,UBERON:0002107,14629.0,3940,3.712944,1603.181097,12621
3,3,d7476ae2-e320-4703-8304-da5c42627e71,10x 3' v3,EFO:0009922,fibroblast,CL:0000057,29-year-old stage,HsapDv:0000123,breast cancer,MONDO:0007254,...,liver,UBERON:0002107,tissue,liver,UBERON:0002107,13740.0,5010,2.742515,347.048082,12621
4,4,d7476ae2-e320-4703-8304-da5c42627e71,10x 3' v3,EFO:0009922,macrophage,CL:0000235,29-year-old stage,HsapDv:0000123,breast cancer,MONDO:0007254,...,liver,UBERON:0002107,tissue,liver,UBERON:0002107,12701.0,4420,2.873529,422.635054,12621
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
158982714,158982714,6f7fd0f1-a2ed-4ff1-80d3-33dde731cbc3,10x 3' v3,EFO:0009922,pvalb GABAergic cortical interneuron,CL:4023018,88-year-old stage,HsapDv:0000214,dementia,MONDO:0001627,...,dorsolateral prefrontal cortex,UBERON:0009834,tissue,brain,UBERON:0000955,8921.0,3751,2.378299,69.158452,35483
158982715,158982715,6f7fd0f1-a2ed-4ff1-80d3-33dde731cbc3,10x 3' v3,EFO:0009922,VIP GABAergic cortical interneuron,CL:4023016,81-year-old stage,HsapDv:0000207,dementia,MONDO:0001627,...,dorsolateral prefrontal cortex,UBERON:0009834,tissue,brain,UBERON:0000955,25528.0,6541,3.902767,112.150177,35483
158982716,158982716,6f7fd0f1-a2ed-4ff1-80d3-33dde731cbc3,10x 3' v3,EFO:0009922,L2/3-6 intratelencephalic projecting glutamate...,CL:4023040,78-year-old stage,HsapDv:0000172,normal,PATO:0000461,...,dorsolateral prefrontal cortex,UBERON:0009834,tissue,brain,UBERON:0000955,49655.0,8319,5.968866,417.691625,35483
158982717,158982717,6f7fd0f1-a2ed-4ff1-80d3-33dde731cbc3,10x 3' v3,EFO:0009922,astrocyte of the cerebral cortex,CL:0002605,75-year-old stage,HsapDv:0000169,normal,PATO:0000461,...,dorsolateral prefrontal cortex,UBERON:0009834,tissue,brain,UBERON:0000955,5736.0,2897,1.979979,44.397389,35483
158982718,158982718,6f7fd0f1-a2ed-4ff1-80d3-33dde731cbc3,10x 3' v3,EFO:0009922,sst GABAergic cortical interneuron,CL:4023017,81-year-old stage,HsapDv:0000207,dementia,MONDO:0001627,...,dorsolateral prefrontal cortex,UBERON:0009834,tissue,brain,UBERON:0000955,5359.0,2630,2.037643,11.685536,35483

In [8]:
with open(f'{cell_gene_dir}/cell_types_breast.txt', 'w') as f:
    f.write(cell_metadata_all['cell_type'].value_counts().to_string())

with open(f'{cell_gene_dir}/tissues_breast.txt', 'w') as f:
    f.write(cell_metadata_all['tissue'].value_counts().to_string())

with open(f'{cell_gene_dir}/tissues_general_breast.txt', 'w') as f:
    f.write(cell_metadata_all['tissue_general'].value_counts().to_string())

In [5]:
df_tree = (
    cell_metadata_all[["tissue_general", "tissue"]]
    .drop_duplicates()
    .sort_values(["tissue_general", "tissue"])
)

print(df_tree)

         tissue_general               tissue
2976709         abdomen              abdomen
3284041         abdomen       abdominal wall
3263076         abdomen        ascitic fluid
3264167         abdomen  parietal peritoneum
3262144         abdomen           peritoneum
...                 ...                  ...
37823949    vasculature     pulmonary artery
40933067    vasculature       thoracic aorta
40932031    vasculature          vasculature
33889275    vasculature                 vein
16986426       yolk sac             yolk sac

[417 rows x 2 columns]

In [8]:
df_counts = (
    cell_metadata_all
    .groupby(["tissue_general", "tissue"])
    .size()
    .reset_index(name="n_cells")
    .sort_values(["tissue_general", "n_cells"], ascending=[True, False])
)
df_counts = df_counts[df_counts["n_cells"] > 0]
print(df_counts)

/tmp/ipykernel_3988261/2319662408.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  cell_metadata_all

      tissue_general               tissue  n_cells
6            abdomen              abdomen   359947
32           abdomen        ascitic fluid   185382
285          abdomen           peritoneum   146002
278          abdomen  parietal peritoneum    14401
8            abdomen       abdominal wall     9899
...              ...                  ...      ...
28409    vasculature        bulb of aorta     7336
28759    vasculature                 vein     4395
28363    vasculature      abdominal aorta     3682
28531    vasculature   inferior vena cava      765
29188       yolk sac             yolk sac   169725

[417 rows x 3 columns]

In [10]:
df_counts.to_csv("../../data/censusxgene/tissue_hierarchy.csv", index=False)