In [2]:
import pandas as pd
import json

In [3]:
# load samples data

filename = "TCGA-BRCA.star_tpm"
df = pd.read_csv(f'../data/{filename}.csv')
df = df.drop(columns=['Unnamed: 0'])
# df = df.drop(columns=['Unnamed: 0.1', 'Unnamed: 0'])
df.head()

,TSPAN6,TNMD,DPM1,SCYL3,C1orf112,FGR,CFH,FUCA2,GCLC,NFYA,...,H3C2,H3C3,TMX2-CTNND1,C3orf36,C8orf44,C8orf44-SGK3,NPBWR1,CDR1,ACTL10,PANO1
0,5.662037,3.376096,6.860140,4.400552,2.845169,3.579965,4.996181,5.614683,4.385652,5.843705,...,0.472176,0.183582,0.158725,1.368154,2.452964,0.000000,0.170310,0.0,0.0,1.122739
1,3.703721,0.463099,7.086452,4.051007,2.426989,2.322361,4.943860,6.539078,4.046404,5.711726,...,1.557631,1.015712,0.056306,0.456491,1.756596,0.029842,0.062398,0.0,0.0,1.243182
2,6.514515,0.000000,6.805072,5.037264,4.043248,2.124130,2.993348,5.119912,3.409907,5.963742,...,0.238787,0.130404,0.253021,0.607863,2.212818,0.000000,0.015640,0.0,0.0,0.604261
3,4.784917,2.328061,6.443071,4.374970,4.162790,3.122375,4.754674,5.608738,3.625691,5.678199,...,1.242755,1.054918,0.026729,0.904735,2.209079,0.028003,0.039419,0.0,0.0,0.536351
4,4.251984,0.435415,6.178436,3.558464,2.589548,1.508581,3.722149,5.224044,3.242221,5.956145,...,0.000000,0.000000,0.206518,0.417704,2.761541,0.000000,1.522257,0.0,0.0,0.389126

In [4]:
# make a list of genes out of columns

genes = pd.Index(df.columns)
genes

Index(['TSPAN6', 'TNMD', 'DPM1', 'SCYL3', 'C1orf112', 'FGR', 'CFH', 'FUCA2',
       'GCLC', 'NFYA',
       ...
       'H3C2', 'H3C3', 'TMX2-CTNND1', 'C3orf36', 'C8orf44', 'C8orf44-SGK3',
       'NPBWR1', 'CDR1', 'ACTL10', 'PANO1'],
      dtype='object', length=20560)

## Match on gene names

In [5]:
# load gene info data, drop duplacates

gene_info_original = pd.read_csv('../data/gene_info_table.csv')
gene_info = gene_info_original.drop(columns=['ensembl_id', 'Unnamed: 0'])
gene_info = gene_info.drop_duplicates()
gene_info.head()

  gene_name       gene_type
0    TSPAN6  protein_coding
1      TNMD  protein_coding
2      DPM1  protein_coding
3     SCYL3  protein_coding
4  C1orf112  protein_coding

In [6]:
# choose 1 gene_type for ambiguous genes

gene_info["priority"] = (gene_info["gene_type"] == "protein_coding").astype(int)
gene_info = gene_info.sort_values(
    ["gene_name", "priority"],
    ascending=[True, False]
)
gene_info = gene_info.drop_duplicates("gene_name")
gene_info = gene_info.drop(columns="priority")

In [7]:
gene_type_map = gene_info.set_index("gene_name")["gene_type"]
mapped_types = genes.map(gene_type_map)
mapped_types

Index(['protein_coding', 'protein_coding', 'protein_coding', 'protein_coding',
       'protein_coding', 'protein_coding', 'protein_coding', 'protein_coding',
       'protein_coding', 'protein_coding',
       ...
       'protein_coding', 'protein_coding', 'protein_coding', 'protein_coding',
       'protein_coding', 'protein_coding', 'protein_coding', 'protein_coding',
       'protein_coding',              nan],
      dtype='object', length=20560)

In [8]:
type_counts = mapped_types.value_counts(dropna=False)
print(type_counts)

protein_coding                        17273
NaN                                    1318
antisense                               602
lncRNA                                  499
lincRNA                                 456
IG_V_gene                               124
TR_V_gene                               101
processed_transcript                     56
IG_V_pseudogene                          46
pseudogene                               20
TR_V_pseudogene                          17
polymorphic_pseudogene                   14
IG_C_gene                                13
IG_C_pseudogene                           7
TR_C_gene                                 4
transcribed_unprocessed_pseudogene        4
IG_J_gene                                 2
transcribed_unitary_pseudogene            1
sense_intronic                            1
misc_RNA                                  1
miRNA                                     1
Name: count, dtype: int64

In [9]:
n_total = len(genes)
n_matched = mapped_types.notna().sum()
n_missing = mapped_types.isna().sum()

print("Total genes:", n_total)
print("Matched:", n_matched)
print("Missing:", n_missing)
print("Match %:", n_matched / n_total * 100)

Total genes: 20560
Matched: 19242
Missing: 1318
Match %: 93.58949416342412

In [10]:
missing_genes = genes[mapped_types.isna()]
print(missing_genes.tolist())

['VPS50', 'TSPOAP1', 'REX1BD', 'KDM7A', 'EEF1AKNMT', 'ELOA', 'ADGRA2', 'MRE11', 'RTF2', 'SARS1', 'EIPR1', 'ADSS2', 'MTREX', 'RIPOR1', 'SLC66A1', 'RIPOR3', 'JADE2', 'NEXMIF', 'HPF1', 'GATB', 'GUCY1B1', 'WAPL', 'BICRA', 'INTS13', 'CCN5', 'BORCS8-MEF2B', 'KARS1', 'PACC1', 'PLPP1', 'ADGRF5', 'HDHD5', 'UFD1', 'ELP1', 'CFAP20', 'BUD23', 'ADGRL1', 'SELENOO', 'NCBP3', 'HACD3', 'MYDGF', 'JADE1', 'TIGAR', 'NRDC', 'CARMIL1', 'PUM3', 'DELE1', 'FYB1', 'DOP1A', 'TUT7', 'FAM234B', 'AK6', 'RTRAF', 'CFAP61', 'GCN1', 'P3H2', 'AARS1', 'ADA2', 'WHRN', 'SMIM24', 'MACROH2A2', 'ATP5F1D', 'CBARP', 'MARCHF2', 'ESS2', 'GRK3', 'SNU13', 'SEPTIN3', 'RSPH14', 'CCDC198', 'SUSD6', 'PCNX1', 'PPP4R3A', 'PRORP', 'RAB5IF', 'PRELID3B', 'PAK5', 'H2BW2', 'RUBCNL', 'ACOD1', 'CIAO3', 'ANTKMT', 'ELOB', 'VPS35L', 'CCN4', 'PYCR3', 'CGB3', 'TLE5', 'YJU2', 'DMAC2', 'NOP53', 'PLPPR2', 'CFAP69', 'GSDME', 'H2AZ2', 'GARS1', 'MINDY4', 'RIC1', 'VSIR', 'TWNK', 'EDRF1', 'NEURL1', 'STN1', 'TASOR2', 'CRACD', 'NSD2', 'ZPR1', 'JHY', 'KMT5B', 'CEP126', 'NECTIN1', 'CARS1', 'ATP5F1B', 'TNS2', 'ADGRD1', 'RIPOR2', 'CRYBG1', 'ARFGEF3', 'ADGRG6', 'BICRAL', 'CCN6', 'TENT5A', 'ERBIN', 'TENT4A', 'CERT1', 'TARS1', 'RARS1', 'MACROH2A1', 'SF3B6', 'DARS1', 'ATP5PB', 'RO60', 'ADGRL2', 'RAB29', 'P3H1', 'PLPPR5', 'RSRP1', 'MESD', 'CCN2', 'RXYLT1', 'STBD1', 'EEF2KMT', 'ECRG4', 'ABITRAM', 'PTPA', 'BBOF1', 'SLF2', 'DENND10', 'ARMH3', 'CFAP58', 'SPART-AS1', 'MTERF2', 'WASHC3', 'TMEM131L', 'TENT4B', 'TMIGD3', 'MTERF4', 'SHLD2', 'PRXL2A', 'SLC66A2', 'SEPTIN7', 'MRM2', 'CYREN', 'TRIR', 'ADGRE5', 'ATG101', 'EEF1AKMT3', 'H2BW1', 'COQ8B', 'ATP5F1E', 'H1-3', 'H1-1', 'H2BC11', 'MYRF-AS1', 'HROB', 'SEPTIN6', 'DMAC2L', 'FNDC11', 'PCNX4', 'TMEM35A', 'INTS11', 'PLAAT1', 'ADGRE2', 'SEM1', 'MTERF1', 'LSM8', 'IFT22', 'CCDC32', 'ICE2', 'MINDY2', 'PGAP6', 'PUDP', 'CRACR2A', 'ANGPTL8', 'NECTIN2', 'MTRES1', 'AFDN', 'IQCN', 'METTL26', 'ATP5IF1', 'SHFL', 'RBSN', 'SELENOS', 'FAAP24', 'JCHAIN', 'H3-3B', 'RIDA', 'MTSS2', 'KHDC4', 'TESMIN', 'PATJ', 'CPLANE2', 'SPART', 'KMT5C', 'SLF1', 'PLAAT4', 'PLAAT2', 'LARGE1', 'LARS1', 'SARAF', 'ERG28', 'DGLUCY', 'NARS1', 'RELCH', 'FBH1', 'SPX', 'RTL8C', 'STK26', 'YARS1', 'TUT4', 'CBLIF', 'POGLUT2', 'CEMIP2', 'BICDL1', 'ADGRB3', 'CEP162', 'ATP5MC2', 'AFG1L', 'NIBAN1', 'WASHC4', 'NUP42', 'MARCHF7', 'ECPAS', 'NIBAN2', 'TRMO', 'CCN3', 'DMAC1', 'THAP12', 'CFAP300', 'SQOR', 'KNL1', 'SELENOI', 'MFSD13A', 'ITPRID2', 'SLC49A4', 'INTS14', 'ZGRF1', 'SEPTIN11', 'SHISAL1', 'SINHCAF', 'ETFBKMT', 'MARCHF9', 'RITA1', 'NUP58', 'ARMH4', 'CLBA1', 'WARS1', 'TLNRD1', 'LINS1', 'SEPTIN12', 'MEAK7', 'UTP4', 'PRELID3A', 'GAREM1', 'RMC1', 'CEP131', 'P3H4', 'RETREG3', 'PLPP2', 'PGGHG', 'DOP1B', 'TIMM29', 'ACP4', 'CCN1', 'AZIN2', 'COP1', 'NECTIN4', 'PRUNE1', 'MINDY1', 'LNPK', 'RETREG2', 'CNOT9', 'MARCHF4', 'GASK1A', 'ADGRG7', 'RUBCN', 'DCAF1', 'MARCHF1', 'MARCHF6', 'OTULINL', 'SHISAL2B', 'H2BC1', 'MMUT', 'ARMT1', 'LINC01558', 'SSC4D', 'NIPSNAP2', 'DIPK2B', 'RADX', 'PLPBP', 'PLPP5', 'NSD3', 'NAPRT', 'MFSD14B', 'AOPEP', 'PLPPR1', 'MIGA2', 'PAXX', 'MINDY3', 'LRMDA', 'HIKESHI', 'KAT14', 'TKFC', 'LTO1', 'TLCD3B', 'EEF1AKMT1', 'ATPSCKMT', 'NKAPD1', 'NOCT', 'TMEM263', 'CENPU', 'TMEM267', 'TLCD4', 'OBI1', 'ATP5F1A', 'LMNTD1', 'ADGRA3', 'ADGRF1', 'ZUP1', 'SDHAF4', 'OTULIN', 'RETREG1', 'TOMM70', 'DIPK1A', 'ATP5MC3', 'ELOC', 'ATP5PF', 'SEPTIN14', 'PIP4P2', 'GRAMD2B', 'NIFK', 'FLACC1', 'C2CD6', 'SAXO1', 'CARNMT1', 'CFAP70', 'MTERF3', 'ADGRG4', 'FCSK', 'ARSL', 'PWWP3B', 'VPS26C', 'TMEM268', 'PRXL2B', 'PRXL2C', 'TENT5B', 'H4C8', 'CATIP', 'EMSY', 'GPAT4', 'CFAP298', 'ATP5MC1', 'CIART', 'ADGRG5', 'DRC7', 'CARMIL2', 'GATD3A', 'CFAP410', 'PLPP7', 'JAML', 'MRNIP', 'PRR35', 'TEDC2', 'LBHD1', 'COA7', 'CZIB', 'PLPP3', 'SELENON', 'ADGRL4', 'FCMR', 'OBSCN-AS1', 'SLC66A3', 'LRATD1', 'WDCP', 'H3-3A', 'COQ8A', 'CFAP221', 'ALPG', 'INAVA', 'TAFA4', 'NAXE', 'TEX55', 'SGO2', 'CCDC191', 'ERICH6', 'CFAP100', 'IGF2BP2-AS1', 'TASOR', 'MELTF', 'H2AZ1', 'ABHD18', 'GUCY1A1', 'GASK1B', 'ICE1', 'PRMT9', 'CFAP97', 'TENT2', 'LINC01600', 'SEPTIN8', 'CGAS', 'TBXT', 'SPATA48', 'H2AC1', 'BMT2', 'TEX47', 'DNAAF5', 'FMC1', 'VIRMA', 'WASHC5', 'MYORG', 'LLCFC1', 'PGAP4', 'CFAP47', 'METTL27', 'SHOC1', 'CARD19', 'DEUP1', 'INTS6L', 'MARCHF8', 'DDIAS', 'DEPP1', 'ATP5F1C', 'ABRAXAS2', 'ENTR1', 'SPACA9', 'BORCS5', 'DIPK1B', 'JCAD', 'PIP4P1', 'CCDC186', 'ERICH6B', 'LARGE2', 'HACD1', 'CEP295', 'BORCS7', 'CCDC182', 'DENND2B', 'CIAO2B', 'CFAP52', 'BEX3', 'BMERB1', 'MARF1', 'CIAO2A', 'PCLAF', 'NEMP1', 'ATP23', 'MARS1', 'TERB2', 'ATP5MG', 'TEPSIN', 'NIBAN3', 'RSKR', 'PROSER3', 'TLCD3A', 'MRPL58', 'ATP5PD', 'FAM234A', 'PLAAT5', 'SPINDOC', 'MAJIN', 'H1-4', 'PPDPFL', 'SEPTIN2', 'CAVIN2', 'MTCL1', 'HJV', 'MUCL3', 'LRATD2', 'LINC01620', 'ATP5ME', 'SLC49A3', 'VXN', 'MINAR1', 'CXCL8', 'CT55', 'RAMAC', 'HEXD', 'GON7', 'TCAF2', 'HARS1', 'PYM1', 'CAVIN4', 'CAVIN3', 'KYAT1', 'FAM241B', 'LKAAEAR1', 'SPATA46', 'CFAP46', 'MRM3', 'DRC3', 'SHLD1', 'CFAP53', 'MCRIP2', 'COPS9', 'MAB21L4', 'PSME3IP1', 'LVRN', 'GRK2', 'MRPL57', 'AHSA2P', 'MFSD4B', 'MICOS10', 'ZNRD2', 'FAM166C', 'ADGRF3', 'CEP83', 'MARCHF10', 'MARCHF3', 'CBY2', 'TENT5D', 'NWD2', 'MIR1-1HG', 'MFSD4A', 'B4GAT1', 'RESF1', 'FAM241A', 'ODAPH', 'ADGRE1', 'SLC66A1L', 'MICOS13', 'CENPS', 'GRAMD2A', 'SUGCT', 'CCDC197', 'MTLN', 'KDF1', 'LINC02694', 'CBLL2', 'TMEM270', 'CRYBG2', 'RPP38-DT', 'SGF29', 'PLAAT3', 'USF3', 'RBIS', 'TCIM', 'PHETA2', 'PRDM16-DT', 'GATD1', 'LINC01561', 'FLJ13224', 'OVOS2', 'NIM1K', 'ERICH5', 'CAVIN1', 'PIDD1', 'HASPIN', 'CRACR2B', 'TMEM94', 'CCDC184', 'LRRC75B', 'CALHM5', 'PRSS42P', 'POGLUT3', 'CCDC185', 'CEP295NL', 'DHFR2', 'LMO7DN', 'H1-8', 'RFLNA', 'CYBC1', 'ERICH3', 'SELENOW', 'PCARE', 'RTL3', 'HNRNPCL4', 'LINC01699', 'WDR97', 'PIK3CD-AS1', 'SEPTIN1', 'ADGRD2', 'MEIOC', 'ITPRID1', 'MTURN', 'ATP5F1EP2', 'ARHGAP45', 'MIGA1', 'H2AC6', 'EIF2S3B', 'LINC01559', 'LINC01555', 'H2AW', 'TLCD5', 'LRRC75A', 'CFAP65', 'ZNF875', 'DIPK2A', 'ADGRB1', 'PNMA8A', 'OGFRP1', 'GET1', 'SHISAL2A', 'PRR34', 'KIAA2012', 'SNORC', 'ADGRG3', 'TSPEAR-AS2', 'SRPRA', 'MCEMP1', 'PRORY', 'PRR36', 'LINC01547', 'SELENOF', 'PRSS40A', 'TMEM121B', 'REC114', 'CABCOCO1', 'FLJ40288', 'TENT5C', 'UTP11', 'H3C13', 'PRR32', 'MARCHF11', 'TAFA1', 'RFLNB', 'LHFPL6', 'ACP7', 'DOCK8-AS1', 'SRARP', 'KMT5A', 'C1QTNF12', 'H2AC20', 'H2AC21', 'H1-5', 'SPEM2', 'STING1', 'TAFA3', 'SEPTIN9', 'H2BC21', 'SEPTIN5', 'B3GALT5-AS1', 'TRARG1', 'H1-10', 'ADSS1', 'NSMCE3', 'H2BC13', 'GALNT17', 'NUPR2', 'PRKN', 'TEDC1', 'TARS3', 'ZSWIM9', 'FAAP100', 'LMNTD2', 'SPATA45', 'INKA1', 'EP400P1', 'MOSMO', 'LINC01405', 'CCDC190', 'DEFB131A', 'MRTFB', 'MINAR2', 'SEPTIN10', 'SMIM29', 'CFAP73', 'SELENOV', 'LINC01551', 'SHTN1', 'H1-7', 'H1-6', 'H2AP', 'PRR27', 'MYMK', 'PERM1', 'B3GLCT', 'EZHIP', 'DIPK1C', 'FAM205C', 'RTL4', 'H1-2', 'FYB2', 'LRRC74B', 'SNHG28', 'RTP5', 'PRSS45P', 'PP7080', 'PEAK3', 'H3-5', 'H2AX', 'CFAP77', 'CCDC9B', 'CLEC20A', 'CFAP54', 'RTL6', 'SAXO2', 'OR56A5', 'CALHM6', 'INSYN2A', 'HACD4', 'CFAP126', 'H1-0', 'JPT1', 'BNIP5', 'TOGARAM2', 'NEMP2', 'ZNF724', 'CCDC189', 'IARS1', 'MFSD14C', 'BORCS6', 'MRTFA', 'SDHAF3', 'ALKAL1', 'LINC01560', 'H2AC13', 'H2AC11', 'ILRUN', 'H2AC7', 'H2BU1', 'TEX43', 'H4C3', 'PCNX3', 'H3C12', 'ADGRA1', 'MIRLET7BHG', 'NOL4L', 'H4C11', 'IRF1-AS1', 'ATP11AUN', 'CPLANE1', 'STPG3', 'CFAP299', 'H4-16', 'INKA2', 'H2BC12', 'ERO1A', 'CYYR1-AS1', 'MARCHF5', 'AFDN-DT', 'PHETA1', 'GET3', 'OGA', 'TCAF1', 'LINC02692', 'TAFA2', 'LINC01565', 'TOGARAM1', 'TEX45', 'SELENOM', 'SELENOT', 'STKLD1', 'CIPC', 'SPOUT1', 'KIFBP', 'CARNMT1-AS1', 'IBA57-DT', 'MIR29B2CHG', 'EEF1AKMT2', 'PLPP4', 'LIN28B-AS1', 'H2AC18', 'H2BC18', 'H3C15', 'RTL8A', 'ARRDC1-AS1', 'CT83', 'NAP1L6P', 'TMEM273', 'MACO1', 'PTPN20', 'TSBP1', 'PJVK', 'SNHG32', 'VARS1', 'MPIG6B', 'LINC01257', 'ZNRD1ASP', 'DISP3', 'RACK1', 'FAM153CP', 'MIR1915HG', 'LINC01556', 'MALRD1', 'INSYN2B', 'SMPD5', 'PNMA8B', 'LINC01545', 'UQCC3', 'ERICH4', 'LINC02716', 'MGAT4D', 'LINC01460', 'ADGRG1', 'INSYN1', 'LINC01597', 'LINC01310', 'SMIM11A', 'ETFRF1', 'PLPP6', 'PCOTH', 'C21orf62-AS1', 'ELOA2', 'FOXL2NB', 'HACD2', 'SELENOH', 'TRGC1', 'ZRSR2P1', 'LINC02693', 'RTL8B', 'ACKR1', 'CCDC183', 'STIMATE', 'LINC01521', 'NAXD', 'ZNF788P', 'SMIM30', 'CDIPTOSP', 'CSKMT', 'LINC01588', 'CRPPA', 'RTL10', 'ALOX12-AS1', 'RNF212B', 'SLC35E2A', 'LINC01644', 'MIF-AS1', 'TAFA5', 'UMAD1', 'GAS8-AS1', 'ZBED8', 'LINC01465', 'TMEM14EP', 'EXOC3-AS1', 'LINC02860', 'LINC01118', 'LINC01124', 'LINC01312', 'LINC01120', 'LINC01422', 'LINC01208', 'LINC01626', 'MYCNUT', 'HRAT92', 'LINC01441', 'ETDB', 'LINC01248', 'MIR548XHG', 'C5orf66', 'SOX1-OT', 'LINC01527', 'PRR29', 'LINC01280', 'LINC01627', 'ZNF812P', 'NTM-AS1', 'CDKN2A-DT', 'NDUFAF8', 'LINC02586', 'PVALEF', 'TAF1A-AS1', 'LINC01427', 'LINC01594', 'MKRN2OS', 'LINC01492', 'LINC01623', 'LINCMD1', 'C9orf135-DT', 'MCRIP1', 'PACRG-AS3', 'P3H2-AS1', 'LINC01529', 'C3orf86', 'C5orf67', 'ODF2-AS1', 'NRIR', 'LAMP5-AS1', 'DDC-AS1', 'SGMS1-AS1', 'CROCC2', 'CYP4F26P', 'PLCG1-AS1', 'MIR217HG', 'CUTALP', 'PP12613', 'DAB1-AS1', 'FAM30A', 'C13orf42', 'LINC01509', 'ATE1-AS1', 'BSN-DT', 'LINC01276', 'LINC01203', 'LINC01247', 'FOCAD-AS1', 'LMCD1-AS1', 'LINC01153', 'MGAT3-AS1', 'LINC01364', 'MROCKI', 'MIR4290HG', 'INKA2-AS1', 'FAM245A', 'FAM174C', 'LINC01350', 'LINC02585', 'LINC01546', 'MIR4432HG', 'D21S2088E', 'FNDC10', 'LIMS1-AS1', 'LINC01344', 'LINC01277', 'LINC01165', 'LINC01548', 'ASTN2-AS1', 'LINC02587', 'DANT1', 'MTCO2P12', 'MIR5689HG', 'LINC01523', 'LINC01501', 'LINC01150', 'CRPPA-AS1', 'LINC01840', 'LINC02603', 'LINC01349', 'MKX-AS1', 'RGPD4-AS1', 'KLHL7-DT', 'LINC01362', 'LINC01293', 'LINC01614', 'LINC01507', 'LNCAROD', 'CSMD2-AS1', 'LINC01098', 'LINC01423', 'CFAP58-DT', 'CFAP97D1', 'GNA14-AS1', 'LINC01516', 'LINC01445', 'LINC01249', 'LINC01363', 'LINC01307', 'LINC01090', 'LINC01198', 'AKAIN1', 'MRPS9-AS1', 'FAM242A', 'FAM238B', 'EP300-AS1', 'LINC01104', 'ELN-AS1', 'AJM1', 'LINC01549', 'KANTR', 'TONSL-AS1', 'LINC01412', 'LINC01162', 'PTGES2-AS1', 'IQCA1-AS1', 'LINC01400', 'PTCHD1-AS', 'LINC01399', 'DIRC3-AS1', 'FAM238A', 'FAM53B-AS1', 'LINC01222', 'B4GALT1-AS1', 'LINC01392', 'LINC01122', 'NRAD1', 'H2BC15', 'LINC01360', 'LINC01425', 'LINC00463', 'DEPDC1-AS1', 'LANCL1-AS1', 'H2BS1', 'OBI1-AS1', 'CCDC188', 'CLDN34', 'MIR3663HG', 'SP2-AS1', 'HRAT17', 'LINC01309', 'MED14OS', 'LINC01287', 'LINC02817', 'BMP7-AS1', 'TMEM30CP', 'HGH1', 'LINC01525', 'LINC01621', 'RPEL1', 'LURAP1L-AS1', 'UBE2R2-AS1', 'LINC01221', 'MSC-AS1', 'LINC01102', 'BARX1-DT', 'LINC00298', 'MSH2-OT1', 'APOA1-AS', 'LINC01553', 'PRRX2-AS1', 'PTCSC2', 'MIR7515HG', 'GACAT3', 'LINC01241', 'DLX2-DT', 'OVAAL', 'LINC01282', 'LINC01554', 'LINC01378', 'BAALC-AS2', 'EDRF1-AS1', 'TMEM26-AS1', 'LINC01519', 'LINC01502', 'LINC01358', 'UNQ6494', 'LINC01304', 'LINC01351', 'LINC01514', 'LINC01318', 'SIRPG-AS1', 'SPATA3-AS1', 'TMEM250', 'LINC01448', 'CASTOR1', 'ATP6V1B1-AS1', 'LINC01119', 'LLPH-DT', 'POM121L7P', 'CASTOR3', 'STPG4', 'DENND6A-AS1', 'LINC01168', 'YAE1', 'LINC01487', 'ATP5MF', 'XACT', 'LINC01324', 'ATP5PO', 'LINC01100', 'NECTIN3-AS1', 'ARPIN', 'LINC01206', 'AADACL2-AS1', 'STMP1', 'CFAP57', 'TMEM35B', 'LINC01322', 'LRRC77P', 'LINC01326', 'ARNTL2-AS1', 'MIR4300HG', 'LINC01513', 'RAB30-DT', 'LINC01096', 'LINC01550', 'LACTB2-AS1', 'H2AJ', 'BAALC-AS1', 'LINC01498', 'PLUT', 'DPH6-DT', 'APELA', 'LINC01197', 'STIMATE-MUSTN1', 'LINC01331', 'SMIM31', 'C8orf34-AS1', 'ATP5MF-PTCD1', 'C5orf66-AS1', 'ZNF436-AS1', 'LINC01093', 'ATP5MGL', 'LINC01179', 'LINC01438', 'LINC01234', 'BMPR1B-DT', 'LINC01187', 'HOXC13-AS', 'C5orf66-AS2', 'LINC01259', 'CARMN', 'OSMR-AS1', 'CCDC37-DT', 'MCPH1-AS1', 'TERB1', 'ARPIN-AP3S2', 'TRMT9B', 'MGC32805', 'TUNAR', 'LINC02148', 'LINC01332', 'LINC01511', 'LINC01017', 'SELENOP', 'LINC01455', 'SMAD1-AS1', 'LINC01181', 'SMIM15-AS1', 'ERVH-1', 'SEMA5A-AS1', 'DCANP1', 'LINC01301', 'CENPS-CORT', 'LINC01385', 'LINC01609', 'WASHC5-AS1', 'C8orf88', 'SHLD3', 'DLGAP2-AS1', 'LINC02209', 'LINC01603', 'LINC01300', 'LINCR-0001', 'KCNIP1-OT1', 'LINC01289', 'LINC01299', 'LINC01947', 'CASC19', 'LINC01111', 'MIR2052HG', 'LINC02584', 'FLJ20021', 'PTPRJ-AS1', 'BORCS8', 'INMT-MINDY4', 'GLYATL1B', 'PRR23D2', 'LINC01489', 'RXYLT1-AS1', 'COA8', 'DNAAF4', 'URB1-AS1', 'PLBD1-AS1', 'ADGRA1-AS1', 'DENND11', 'CLIP1-AS1', 'FOXG1-AS1', 'LINC01154', 'KRT73-AS1', 'MIR4307HG', 'INAFM1', 'LINC01490', 'MGAM2', 'LINC02588', 'LHX5-AS1', 'TEX49', 'TESC-AS1', 'LINC00239', 'LINC01500', 'LINC01397', 'LINC01579', 'SALRNA1', 'LINC01467', 'BUB1B-PAK6', 'ZHX1-C8orf76', 'TGIF2-RAB5IF', 'MGC15885', 'LINC01169', 'UBE2Q2L', 'LINC01583', 'ST20-AS1', 'LINGO1-AS1', 'PCSK6-AS1', 'THSD4-AS1', 'LINC01571', 'LINC01413', 'CCDC187', 'KDM7A-DT', 'ARMH2', 'SCX', 'KCNJ18', 'INSYN1-AS1', 'CISTR', 'STAM-AS1', 'LINC01541', 'LINC01243', 'LINC01227', 'SERTM2', 'CASC22', 'ARLNC1', 'LINC01254', 'LINC01311', 'LINC01416', 'LINC01633', 'MKRN3-AS1', 'LINC01228', 'LINC01616', 'PYCARD-AS1', 'PRSS46P', 'LINC01477', 'MIR3976HG', 'GFY', 'MMP25-AS1', 'LINC01569', 'CCER2', 'C19orf84', 'TMEM238L', 'LINC01543', 'ABHD15-AS1', 'LINC01444', 'NOTCH2NLA', 'SEPTIN4-AS1', 'LINC01476', 'PCAT18', 'LINC01443', 'DSG1-AS1', 'TBC1D29P', 'FARSA-AS1', 'LINC01180', 'LINC01532', 'TCF4-AS1', 'CTB-30L5.1', 'MIR2117HG', 'PARD6G-AS1', 'LINC01415', 'LINC01478', 'UPK3BL1', 'FDX2', 'ERVK-28', 'LINC01539', 'RUNDC3A-AS1', 'SCGB1C2', 'LRRC2-AS1', 'MIR4453HG', 'MAN1B1-DT', 'PTOV1-AS2', 'OPN1MW3', 'CT45A10', 'NOP53-AS1', 'ZIM2-AS1', 'BICRA-AS1', 'RNF225', 'FMC1-LUC7L2', 'ZNF559-ZNF177', 'NCBP2AS2', 'H4C15', 'HEATR9', 'FBXW7-AS1', 'H4C14', 'CT45A9', 'TLCD4-RWDD3', 'LINC01109', 'NBPF19', 'ATP2B1-AS1', 'H2AC19', 'NBPF26', 'H3-2', 'SFTPD-AS1', 'H2BC14', 'LL21NC02-21A1.1', 'WI2-87327B8.2', 'H3C8', 'H2AB1', 'SEC22B2P', 'H4C6', 'H2BC17', 'H3C6', 'H2AC12', 'H4C13', 'H2AC15', 'H3C11', 'H2BC9', 'H3C1', 'PRH1-PRR4', 'H4C9', 'H2AC14', 'H2BC3', 'H2AC16', 'H4C5', 'H2AC8', 'H4C4', 'H2AB3', 'H3C7', 'H2AC4', 'H4C1', 'H2AC17', 'H4C2', 'H3C10', 'CH507-145C22.1', 'CEP83-DT', 'AGAP14P', 'CH507-9B2.8', 'CH507-42P11.6', 'ERICD', 'LINC01374', 'LINC01348', 'SCAANT1', 'LINC01242', 'JADRR', 'LINC01202', 'ELDR', 'TMEM272', 'LINC01127', 'LINC00997', 'DNAJB5-DT', 'SEPSECS-AS1', 'LINC01080', 'LINC01394', 'LINC01260', 'PANO1']

## Using another table for mapping to ensemble id

In [11]:
# another gene_info for missed genes

gene_ensembl = pd.read_csv('../data/gene_info.csv')
gene_ensembl.head()

   Unnamed: 0  soma_joinid       feature_id feature_name  feature_length
0           0            0  ENSG00000121410         A1BG            3999
1           1            1  ENSG00000268895     A1BG-AS1            3374
2           2            2  ENSG00000148584         A1CF            9603
3           3            3  ENSG00000175899          A2M            6318
4           4            4  ENSG00000245105      A2M-AS1            2948

In [12]:
symbol_to_ens_map = gene_ensembl.set_index("feature_name")["feature_id"]
missing_ens = missing_genes.map(symbol_to_ens_map)


# genes_ens = pd.Index(missing_genes)
# ensembl_ids = genes_ens.map(symbol_to_ens)

# genes_ens[ensembl_ids.isna()] # check if all are mapped
missing_ens.notna().mean()

1.0

In [13]:
gene_info_ens = gene_info_original.drop(columns=['gene_name', 'Unnamed: 0'])
gene_info_ens = gene_info_ens.drop_duplicates()
gene_info_ens.head()

        ensembl_id       gene_type
0  ENSG00000000003  protein_coding
1  ENSG00000000005  protein_coding
2  ENSG00000000419  protein_coding
3  ENSG00000000457  protein_coding
4  ENSG00000000460  protein_coding

In [14]:
# choose 1 gene_type for ambiguous genes

gene_info_ens["priority"] = (gene_info_ens["gene_type"] == "protein_coding").astype(int)
gene_info_ens = gene_info_ens.sort_values(
    ["ensembl_id", "priority"],
    ascending=[True, False]
)
gene_info_ens = gene_info_ens.drop_duplicates("ensembl_id")
gene_info_ens = gene_info_ens.drop(columns="priority")

# creat mapping
gene_type_map_ens = gene_info_ens.set_index("ensembl_id")["gene_type"]

In [15]:
missing_types_from_ens = missing_ens.map(gene_type_map_ens)

In [16]:
# fill in missing genes with new mapping
mapped_types = pd.Series(mapped_types, index=genes)
mapped_types.loc[missing_genes] = missing_types_from_ens.values

mapped_types

TSPAN6          protein_coding
TNMD            protein_coding
DPM1            protein_coding
SCYL3           protein_coding
C1orf112        protein_coding
                     ...
C8orf44-SGK3    protein_coding
NPBWR1          protein_coding
CDR1            protein_coding
ACTL10          protein_coding
PANO1                      NaN
Length: 20560, dtype: object

In [17]:
# see how many genes are in categories
mapped_types.value_counts(dropna=False)

protein_coding                        18234
antisense                               714
lincRNA                                 659
lncRNA                                  523
IG_V_gene                               124
TR_V_gene                               101
processed_transcript                     62
IG_V_pseudogene                          46
pseudogene                               28
TR_V_pseudogene                          17
polymorphic_pseudogene                   14
IG_C_gene                                13
IG_C_pseudogene                           7
TR_C_gene                                 5
transcribed_unprocessed_pseudogene        4
IG_J_gene                                 2
unprocessed_pseudogene                    2
transcribed_unitary_pseudogene            1
sense_intronic                            1
misc_RNA                                  1
miRNA                                     1
NaN                                       1
Name: count, dtype: int64

## Choose only protein-coding genes

In [18]:
protein_coding_genes = mapped_types[mapped_types == "protein_coding"].index.tolist()
len(protein_coding_genes)

18234

In [19]:
with open(f"../data/{filename}_gene_list.json", "w") as f:
    json.dump(protein_coding_genes, f)