In [1]:
import json
import pandas as pd

In [2]:
def load_gene_runs(filepath):
    runs = []
    with open(filepath) as f:
        for line in f:
            runs.append(json.loads(line))
    return runs

runs = load_gene_runs("../analysis/training_shap.jsonl")

In [3]:
# top 1000 genes from each fold
gene_lists = [run["genes"][:1000] for run in runs]
top_concat = [element for gene_list in gene_lists for element in gene_list]

gene_sets = {run["run_name"]: set(run["genes"]) for run in runs}
common_all = set.intersection(*gene_sets.values())

top_concat.extend(common_all)
len(set(top_concat))

3256

In [4]:
df = pd.read_csv('../data/0_data_for_mlp/TCGA-BRCA.star_tpm.csv')

In [5]:
df.head()

,Unnamed: 0,TNMD,DPM1,SCYL3,C1orf112,FGR,CFH,FUCA2,GCLC,NFYA,...,RP1-20C7.7,RP11-57C19.8,C8orf44,C8orf44-SGK3,NPBWR1,RP11-18C24.9,CDR1,ACTL10,RP11-159G9.5,RP11-384O8.2
0,TCGA-D8-A146,3.376096,6.860140,4.400552,2.845169,3.579965,4.996181,5.614683,4.385652,5.843705,...,0.0,0.0,2.452964,0.000000,0.170310,0.0,0.0,0.0,0.0,0.151989
1,TCGA-AQ-A0Y5,0.463099,7.086452,4.051007,2.426989,2.322361,4.943860,6.539078,4.046404,5.711726,...,0.0,0.0,1.756596,0.029842,0.062398,0.0,0.0,0.0,0.0,0.972619
2,TCGA-C8-A274,0.000000,6.805072,5.037264,4.043248,2.124130,2.993348,5.119912,3.409907,5.963742,...,0.0,0.0,2.212818,0.000000,0.015640,0.0,0.0,0.0,0.0,0.389677
3,TCGA-BH-A0BD,2.328061,6.443071,4.374970,4.162790,3.122375,4.754674,5.608738,3.625691,5.678199,...,0.0,0.0,2.209079,0.028003,0.039419,0.0,0.0,0.0,0.0,0.160533
4,TCGA-B6-A1KC,0.435415,6.178436,3.558464,2.589548,1.508581,3.722149,5.224044,3.242221,5.956145,...,0.0,0.0,2.761541,0.000000,1.522257,0.0,0.0,0.0,0.0,1.312200

In [ ]:
columns = list(set(top_concat))
columns.insert(0, 'Unnamed: 0')
df_selected = df[columns]

In [7]:
df

,Unnamed: 0,NXPH2,C17orf77,CIB3,CHMP6,IL18,ALDH18A1,PSD3,AGO2,THTPA,...,SLMAP,GSTM1,MTG2,ALS2CL,FGL1,AFG1L,MESP1,CLK3,HMG20B,TBC1D2B
0,TCGA-D8-A146,0.524264,1.234563,1.365581,4.644197,3.384409,7.230143,6.042830,3.345325,3.459904,...,4.785069,0.037453,4.921627,2.320918,0.028569,1.878294,1.843542,3.262568,6.649710,4.447447
1,TCGA-AQ-A0Y5,0.032665,0.000000,1.034004,3.737622,3.259860,7.743825,2.674709,3.813966,2.391548,...,5.019911,5.754449,5.635360,2.535257,1.011138,1.892430,0.607958,3.092174,6.041026,4.710718
2,TCGA-C8-A274,0.162081,0.023752,4.964061,3.882389,5.089807,8.024773,3.262553,3.758794,2.664597,...,4.009732,0.026163,4.730466,2.000325,0.039700,1.610700,5.098495,2.440474,6.094530,4.529040
3,TCGA-BH-A0BD,0.000000,0.059217,2.010135,4.304861,3.363536,7.580265,2.917145,3.866186,3.328865,...,4.164223,0.096936,4.501414,2.655214,1.606395,1.340619,1.139862,2.920770,6.030685,4.836242
4,TCGA-B6-A1KC,0.021195,0.000000,1.700706,3.425768,2.422610,6.156136,4.164851,4.248269,2.989030,...,4.767671,0.000000,3.676809,1.705314,0.034497,1.359577,0.345056,2.807746,5.252151,4.073246
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1090,TCGA-BH-A0EI,0.000000,0.000000,0.797179,4.528202,2.362245,7.022815,2.990465,3.881165,3.153222,...,4.512973,5.134295,4.815391,1.092952,0.000000,1.631756,5.381024,3.237197,6.186580,5.394037
1091,TCGA-E2-A1IO,0.000000,0.000000,2.872494,4.997762,3.469482,7.057872,4.230103,4.667722,2.961697,...,4.057788,0.000000,5.322667,2.244339,0.031395,1.870463,2.459327,2.803330,6.174269,5.221889
1092,TCGA-E2-A15R,0.075464,0.000000,1.064607,4.792059,2.109227,7.324227,4.203554,3.980464,3.845570,...,5.111904,7.651883,5.670795,1.271187,0.141302,1.589428,0.596363,3.150218,6.514338,4.862074
1093,TCGA-B6-A0IP,0.244156,0.000000,2.128590,4.740701,3.999829,7.095890,5.673944,3.821139,3.065521,...,4.375144,0.000000,5.082745,2.226077,0.021622,1.598222,0.762136,3.346900,6.694769,3.976675
1094,TCGA-A1-A0SN,0.032947,0.000000,1.511114,4.580314,5.096376,7.096181,4.990043,4.715487,3.067226,...,4.668233,0.000000,3.981168,2.561448,0.000000,1.204767,2.415975,2.761817,6.948723,4.819275

In [ ]:
df_selected.to_csv(f"../data/0_data_for_mlp_testing/top_shap_3k_training.csv", index=False)