In [11]:
import pandas as pd

In [12]:
read_directory = '../data/results_gathered'
save_directory = '../data/results_gathered/baselines.csv'

In [13]:
filenames = ['mlp', 'mlp_big', 'snn', 'snn_big']

In [21]:
dfs = []

for filename in filenames:
    path = f'{read_directory}/results_gathered_{filename}.csv'
    df = pd.read_csv(path, index_col=0)
    df['baseline'] = filename
    dfs.append(df)

result_df = pd.concat(dfs, ignore_index=True)

In [22]:
result_df = result_df.sort_values(by=["c_index_avg"], ascending=False)

In [23]:
def parse_experiment(exp):
    out = {
        "data_type": "raw",
        "normalization": None,
        "embedding_model": None,
        "hvg": 0
    }
    
    if "scgpt_adata" in exp:
        out["data_type"] = "embedding"
        
        if "pancancer" in exp:
            out["embedding_model"] = "pancancer"
        elif "whole_human" in exp:
            out["embedding_model"] = "whole_human"
        
        if "hvg_" in exp:
            out["hvg"] = int(exp.split("hvg_")[1].split(".")[0])

    if "tpm" in exp:
        out["normalization"] = "TPM"
    elif "counts" in exp:
        out["normalization"] = "counts"
    
    return pd.Series(out)


result_df = result_df.join(result_df["experiment"].apply(parse_experiment))

In [24]:
result_df

,experiment,loss_avg,loss_std,c_index_avg,c_index_std,c_index_ipcw_avg,c_index_ipcw_std,baseline,data_type,normalization,embedding_model,hvg
42,Final_results_TCGA-BRCA.star_tpm.csv,15.844594,4.406341,0.730481,0.083589,0.643454,0.122930,snn_big,raw,TPM,None,0
28,Final_results_TCGA-BRCA.star_tpm.csv,6.124241,1.113554,0.728785,0.080471,0.625501,0.131519,snn,raw,TPM,None,0
43,Final_results_TCGA-BRCA.star_counts.csv,17.282411,3.786621,0.724132,0.066134,0.667841,0.120472,snn_big,raw,counts,None,0
0,Final_results_TCGA-BRCA.star_tpm.csv,3.727684,0.846379,0.722072,0.077890,0.626490,0.112428,mlp,raw,TPM,None,0
1,Final_results_TCGA-BRCA.star_counts.csv,3.595652,0.481881,0.717970,0.049064,0.626261,0.075343,mlp,raw,counts,None,0
29,Final_results_TCGA-BRCA.star_counts.csv,6.570696,0.719155,0.713689,0.041754,0.634991,0.083398,snn,raw,counts,None,0
14,Final_results_TCGA-BRCA.star_counts.csv,4.832736,0.937835,0.712360,0.055748,0.635052,0.094081,mlp_big,raw,counts,None,0
15,Final_results_TCGA-BRCA.star_tpm.csv,4.735203,1.077261,0.708060,0.088001,0.628517,0.120827,mlp_big,raw,TPM,None,0
30,Final_results_scgpt_adata_TCGA-BRCA.star_count...,3.371445,0.695338,0.646102,0.101684,0.537738,0.118326,snn,embedding,counts,pancancer,3000
2,Final_results_scgpt_adata_TCGA-BRCA.star_tpm_p...,3.066455,0.366001,0.645853,0.099764,0.554217,0.056885,mlp,embedding,TPM,pancancer,6000
3,Final_results_scgpt_adata_TCGA-BRCA.star_tpm_w...,3.162002,0.454541,0.644945,0.107021,0.532533,0.090655,mlp,embedding,TPM,whole_human,6000
44,Final_results_scgpt_adata_TCGA-BRCA.star_count...,5.993538,2.145127,0.642559,0.121957,0.540343,0.125937,snn_big,embedding,counts,pancancer,3000
45,Final_results_scgpt_adata_TCGA-BRCA.star_count...,5.875208,0.755728,0.638438,0.051748,0.514720,0.089390,snn_big,embedding,counts,whole_human,3000
46,Final_results_scgpt_adata_TCGA-BRCA.star_count...,5.554816,1.976955,0.638127,0.134144,0.556525,0.179310,snn_big,embedding,counts,pancancer,6000
31,Final_results_scgpt_adata_TCGA-BRCA.star_count...,3.269325,0.434086,0.635562,0.036943,0.501154,0.094354,snn,embedding,counts,whole_human,3000
47,Final_results_scgpt_adata_TCGA-BRCA.star_tpm_w...,7.173450,1.516980,0.635498,0.064306,0.542148,0.140188,snn_big,embedding,TPM,whole_human,0
32,Final_results_scgpt_adata_TCGA-BRCA.star_count...,3.200984,0.642405,0.630253,0.115705,0.547594,0.172167,snn,embedding,counts,pancancer,6000
48,Final_results_scgpt_adata_TCGA-BRCA.star_tpm_w...,5.993456,1.685559,0.629914,0.075810,0.559183,0.038347,snn_big,embedding,TPM,whole_human,6000
49,Final_results_scgpt_adata_TCGA-BRCA.star_tpm_p...,6.235021,0.754763,0.627796,0.070720,0.552793,0.037423,snn_big,embedding,TPM,pancancer,6000
33,Final_results_scgpt_adata_TCGA-BRCA.star_tpm_w...,3.457530,0.387046,0.622481,0.073854,0.534632,0.129676,snn,embedding,TPM,whole_human,0
4,Final_results_scgpt_adata_TCGA-BRCA.star_tpm_w...,3.167075,0.403777,0.622131,0.078496,0.556892,0.135118,mlp,embedding,TPM,whole_human,0
34,Final_results_scgpt_adata_TCGA-BRCA.star_tpm_p...,3.273047,0.354774,0.620339,0.081043,0.531358,0.029281,snn,embedding,TPM,pancancer,6000
16,Final_results_scgpt_adata_TCGA-BRCA.star_tpm_p...,4.978888,0.818582,0.617363,0.109306,0.538261,0.087439,mlp_big,embedding,TPM,pancancer,6000
5,Final_results_scgpt_adata_TCGA-BRCA.star_count...,3.157064,0.452801,0.617047,0.092576,0.527941,0.088164,mlp,embedding,counts,pancancer,3000
6,Final_results_scgpt_adata_TCGA-BRCA.star_count...,3.114444,0.451487,0.615747,0.104078,0.554820,0.169206,mlp,embedding,counts,pancancer,6000
7,Final_results_scgpt_adata_TCGA-BRCA.star_count...,3.113357,0.363714,0.609946,0.076899,0.487926,0.097823,mlp,embedding,counts,whole_human,3000
35,Final_results_scgpt_adata_TCGA-BRCA.star_tpm_w...,3.509421,0.325701,0.606396,0.031628,0.504611,0.082088,snn,embedding,TPM,whole_human,3000
36,Final_results_scgpt_adata_TCGA-BRCA.star_tpm_w...,3.281766,0.555658,0.603439,0.097985,0.530110,0.066379,snn,embedding,TPM,whole_human,6000
8,Final_results_scgpt_adata_TCGA-BRCA.star_count...,3.119610,0.347489,0.602774,0.034720,0.554862,0.106598,mlp,embedding,counts,pancancer,0
17,Final_results_scgpt_adata_TCGA-BRCA.star_tpm_w...,5.143542,0.776545,0.602573,0.079884,0.539646,0.073061,mlp_big,embedding,TPM,whole_human,6000
18,Final_results_scgpt_adata_TCGA-BRCA.star_count...,4.683387,0.993086,0.596765,0.061172,0.476983,0.122269,mlp_big,embedding,counts,whole_human,6000
37,Final_results_scgpt_adata_TCGA-BRCA.star_tpm_p...,3.304430,0.437627,0.596119,0.038490,0.516228,0.048423,snn,embedding,TPM,pancancer,3000
50,Final_results_scgpt_adata_TCGA-BRCA.star_tpm_w...,6.569264,0.801453,0.595605,0.030628,0.507472,0.051855,snn_big,embedding,TPM,whole_human,3000
9,Final_results_scgpt_adata_TCGA-BRCA.star_tpm_p...,3.142749,0.388756,0.592070,0.039067,0.529381,0.052399,mlp,embedding,TPM,pancancer,3000
51,Final_results_scgpt_adata_TCGA-BRCA.star_tpm_p...,6.066222,0.940939,0.590406,0.024799,0.540419,0.028092,snn_big,embedding,TPM,pancancer,3000
52,Final_results_scgpt_adata_TCGA-BRCA.star_count...,5.779927,1.646602,0.585960,0.035523,0.546548,0.150467,snn_big,embedding,counts,pancancer,0
38,Final_results_scgpt_adata_TCGA-BRCA.star_count...,3.291849,0.363233,0.580650,0.029582,0.521547,0.138613,snn,embedding,counts,pancancer,0
10,Final_results_scgpt_adata_TCGA-BRCA.star_tpm_p...,3.198738,0.280679,0.580627,0.098134,0.536625,0.079569,mlp,embedding,TPM,pancancer,0
53,Final_results_scgpt_adata_TCGA-BRCA.star_tpm_p...,6.957943,1.733482,0.575821,0.078782,0.552948,0.075400,snn_big,embedding,TPM,pancancer,0
39,Final_results_scgpt_adata_TCGA-BRCA.star_tpm_p...,3.400292,0.405088,0.574922,0.114326,0.553886,0.110946,snn,embedding,TPM,pancancer,0
19,Final_results_scgpt_adata_TCGA-BRCA.star_tpm_w...,5.446637,0.898190,0.572753,0.086887,0.549407,0.134902,mlp_big,embedding,TPM,whole_human,0
54,Final_results_scgpt_adata_TCGA-BRCA.star_count...,6.530573,1.147461,0.568519,0.072349,0.447005,0.097625,snn_big,embedding,counts,whole_human,6000
20,Final_results_scgpt_adata_TCGA-BRCA.star_count...,4.805788,1.430248,0.568188,0.093650,0.588396,0.051611,mlp_big,embedding,counts,pancancer,0
11,Final_results_scgpt_adata_TCGA-BRCA.star_tpm_w...,3.219736,0.303390,0.567639,0.058785,0.464536,0.065713,mlp,embedding,TPM,whole_human,3000
40,Final_results_scgpt_adata_TCGA-BRCA.star_count...,3.456833,0.561498,0.554724,0.069329,0.450013,0.098323,snn,embedding,counts,whole_human,6000
21,Final_results_scgpt_adata_TCGA-BRCA.star_count...,5.070035,1.203299,0.553755,0.161841,0.572564,0.153922,mlp_big,embedding,counts,pancancer,6000
12,Final_results_scgpt_adata_TCGA-BRCA.star_count...,3.217420,0.430270,0.549219,0.081206,0.423072,0.106538,mlp,embedding,counts,whole_human,6000
22,Final_results_scgpt_adata_TCGA-BRCA.star_count...,4.885273,0.494701,0.544751,0.061097,0.540594,0.075945,mlp_big,embedding,counts,whole_human,3000
23,Final_results_scgpt_adata_TCGA-BRCA.star_count...,5.154583,1.114022,0.535992,0.131675,0.476374,0.078683,mlp_big,embedding,counts,pancancer,3000
13,Final_results_scgpt_adata_TCGA-BRCA.star_count...,3.160083,0.366565,0.534306,0.096019,0.528364,0.050787,mlp,embedding,counts,whole_human,0
24,Final_results_scgpt_adata_TCGA-BRCA.star_count...,5.471292,0.760811,0.524509,0.077578,0.496859,0.126529,mlp_big,embedding,counts,whole_human,0
25,Final_results_scgpt_adata_TCGA-BRCA.star_tpm_p...,5.753322,1.229687,0.519839,0.091527,0.478256,0.079940,mlp_big,embedding,TPM,pancancer,0
26,Final_results_scgpt_adata_TCGA-BRCA.star_tpm_p...,4.733875,0.639869,0.515608,0.090688,0.471161,0.058491,mlp_big,embedding,TPM,pancancer,3000
27,Final_results_scgpt_adata_TCGA-BRCA.star_tpm_w...,5.238378,0.943624,0.513183,0.105053,0.535459,0.115505,mlp_big,embedding,TPM,whole_human,3000
41,Final_results_scgpt_adata_TCGA-BRCA.star_count...,3.350774,0.368758,0.513109,0.084505,0.541830,0.089497,snn,embedding,counts,whole_human,0
55,Final_results_scgpt_adata_TCGA-BRCA.star_count...,6.649315,0.657693,0.512416,0.087380,0.564250,0.081134,snn_big,embedding,counts,whole_human,0

In [25]:
result_df = result_df[result_df['normalization'] == 'TPM']

In [26]:
result_df.to_csv(save_directory)

In [28]:
raw_vs_emb = (
    result_df.groupby("data_type")
      .agg(
          c_index_mean=("c_index_avg", "mean"),
          c_index_std=("c_index_avg", "std"),
          ipcw_mean=("c_index_ipcw_avg", "mean"),
          ipcw_std=("c_index_ipcw_avg", "std")
      )
)

raw_vs_emb

           c_index_mean  c_index_std  ipcw_mean  ipcw_std
data_type
embedding      0.594722     0.037766   0.529673  0.026735
raw            0.722350     0.010195   0.630991  0.008403

In [23]:
arch_summary = (
    result_df.groupby("baseline")
      .agg(
          c_index_mean=("c_index_avg", "mean"),
          c_index_std=("c_index_avg", "std")
      )
      .sort_values("c_index_mean", ascending=False)
)

arch_summary

          c_index_mean  c_index_std
baseline
snn_big       0.621119     0.057789
snn           0.616184     0.056663
mlp           0.615882     0.054719
mlp_big       0.577550     0.065275

In [33]:
arch_vs_data_summary = (
    result_df
    .groupby(["data_type", "baseline"])
    .agg(
        c_index_mean=("c_index_avg", "mean"),
        # c_index_std=("c_index_avg", "std"),
        icpw_mean=("c_index_ipcw_avg", "mean")
        # icpw_std=("c_index_ipcw_avg", "std")
    )
    .sort_values("c_index_mean", ascending=False)
)

arch_vs_data_summary

                    c_index_mean  icpw_mean
data_type baseline
raw       snn_big       0.730481   0.643454
          snn           0.728785   0.625501
          mlp           0.722072   0.626490
          mlp_big       0.708060   0.628517
embedding snn_big       0.609173   0.542494
          mlp           0.608877   0.529031
          snn           0.603949   0.528471
          mlp_big       0.556886   0.518698

In [26]:
arch_vs_data_summary = (
    result_df
    .groupby(["baseline", "data_type"])
    .agg(
        c_index_mean=("c_index_avg", "mean"),
        c_index_std=("c_index_avg", "std")
    )
    .round(3)
    .unstack("data_type")
)

arch_vs_data_summary

          c_index_mean        c_index_std
data_type    embedding    raw   embedding    raw
baseline
mlp              0.599  0.720       0.035  0.003
mlp_big          0.555  0.710       0.036  0.003
snn              0.599  0.721       0.038  0.011
snn_big          0.603  0.727       0.039  0.004

In [31]:
hvg_summary = (
    result_df[result_df["data_type"] == "embedding"]
    .groupby("hvg")
    .agg(
        c_index_mean=("c_index_avg", "mean"),
        c_index_std=("c_index_avg", "std"),
        ipcw_mean=("c_index_ipcw_avg", "mean"),
        ipcw_std=("c_index_ipcw_avg", "std"),
    )
    .sort_index()
)

hvg_summary

      c_index_mean  c_index_std  ipcw_mean  ipcw_std
hvg
0         0.588009     0.037535   0.538099  0.025530
3000      0.572128     0.037267   0.508658  0.028245
6000      0.624028     0.016496   0.542263  0.011490

In [34]:
raw_vs_emb = (
    result_df.groupby("embedding_model")
      .agg(
          c_index_mean=("c_index_avg", "mean"),
          c_index_std=("c_index_avg", "std"),
          ipcw_mean=("c_index_ipcw_avg", "mean"),
          ipcw_std=("c_index_ipcw_avg", "std")
      )
)

raw_vs_emb

                 c_index_mean  c_index_std  ipcw_mean  ipcw_std
embedding_model
pancancer            0.588064     0.039528   0.529628  0.028209
whole_human          0.601380     0.036373   0.529719  0.026434